### ISSUE TITLE
Current Inventory-Rollback build not working with Spigot 1.18

### ISSUE THREAD

**Issue by ASchneider-GitHub** [danjono/InventoryRollback#60]
The most recent build of Inventory-Rollback doesn't work with the 1.18 release of Spigot.

Output of `icanhasbukkit`:
> This server is running CraftBukkit version 3334-Spigot-a5dea1c-a008701 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)

Steps to reproduce:
1. Install Inventory-Rollback v1.4.0
2. Perform an action that triggers a backup
3. Run the command `/ir restore <playerName>`
4. Click on an item in the GUI

The following error trace is thrown:
```
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
    at java.base/java.lang.Class.getMethod(Class.java:2227)
    at me.danjono.inventoryrollback.reflections.NBT.getString(NBT.java:132)
    at me.danjono.inventoryrollback.reflections.NBT.hasUUID(NBT.java:20)
    at me.danjono.inventoryrollback.listeners.ClickGUI.mainMenu(ClickGUI.java:101)
    at me.danjono.inventoryrollback.listeners.ClickGUI.onInventoryClick(ClickGUI.java:78)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2437)
    at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58)
    at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13)
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
    at net.minecraft.server.TickTask.run(SourceFile:18)
    at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1157)
    at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
    at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
    at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1136)
    at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1129)
    at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:110)
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1112)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1037)
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Tuurkevg** [comment]
same here...

[12:23:51 INFO]: srvg issued server command: /ir restore pjvdb2003
[12:23:51 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[12:23:51 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.reflections.NBT.setString(NBT.java:28)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.Buttons.createLogTypeButton(Buttons.java:215)

[12:23:51 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:23:51 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:23:51 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[12:23:51 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[12:23:51 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.reflections.NBT.setString(NBT.java:28)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.Buttons.createLogTypeButton(Buttons.java:215)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.MainMenu.getMenu(MainMenu.java:57)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.commands.Commands.onCommand(Commands.java:50)
[12:23:51 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:23:51 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:23:51 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:23:51 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:23:51 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:23:51 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[12:23:51 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[12:23:51 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.reflections.NBT.setString(NBT.java:28)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.Buttons.createLogTypeButton(Buttons.java:216)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.MainMenu.getMenu(MainMenu.java:57)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.commands.Commands.onCommand(Commands.java:50)
[12:23:51 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:23:51 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:23:51 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:23:51 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:23:51 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:23:51 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[12:23:51 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[12:23:51 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.reflections.NBT.setString(NBT.java:28)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.Buttons.createLogTypeButton(Buttons.java:215)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.MainMenu.getMenu(MainMenu.java:62)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.commands.Commands.onCommand(Commands.java:50)
[12:23:51 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:23:51 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:23:51 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:23:51 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:23:51 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:23:51 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[12:23:51 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[12:23:51 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.reflections.NBT.setString(NBT.java:28)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.Buttons.createLogTypeButton(Buttons.java:216)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.MainMenu.getMenu(MainMenu.java:62)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.commands.Commands.onCommand(Commands.java:50)
[12:23:51 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:23:51 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:23:51 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:23:51 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:23:51 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:23:51 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[12:23:51 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[12:23:51 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.reflections.NBT.setString(NBT.java:28)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.Buttons.createLogTypeButton(Buttons.java:215)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.MainMenu.getMenu(MainMenu.java:67)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.commands.Commands.onCommand(Commands.java:50)
[12:23:51 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:23:51 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:23:51 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[12:23:51 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:23:51 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:23:51 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:23:51 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[12:23:51 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[12:23:51 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:23:51 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[12:23:51 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[12:23:51 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.reflections.NBT.setString(NBT.java:28)
[12:23:51 WARN]: at InventoryRollback-1.4.0.jar//me.danjono.inventoryrollback.gui.Buttons.createLogTypeButton(Buttons.java:216)
er.java:317)
[12:23:57 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kalebchoi** [comment]
This project seems to be abandoned. However, there is an updated fork available [here](https://www.spigotmc.org/resources/inventory-rollback-plus-1-8-1-18-x.85811/)

**Comment by libexus** [comment]
Please note that the fork @kalebchoi mentioned is **not licensed under the MIT Licence** anymore, [but is all rights reserved](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/blob/main/LICENSE) (The MIT Licence allows this).

In case you don't like this, I found another fork that still uses the MIT License and **supports 1.18**: [Inventory Rollback: Continued](https://github.com/Sidpatchy/InventoryRollback-Continued)

From the [README:](https://github.com/Sidpatchy/InventoryRollback-Continued/blob/master/README.md) 
> Danjono, the plugin's original dev, seems to have disappeared off the face of the earth. I intend to maintain this fork in their absence. I will be manually merging pull requests (which I believe are of benefit to the plugin) from the original repo
> 
> Additionally the author of the other Inventory Rollback fork has licensed all their changes as all rights reserved. I disagree with that philosophy, the mere ability to publish our forks should demonstrate that copyleft licenses are a good thing

This means that once @danjono comes back, the changes can be merged back into the original plugin and there is no need to maintain the forks anymore.

**Comment by kalebchoi** [comment]
> Please note that the fork @kalebchoi mentioned is **not licensed under the MIT Licence** anymore, [but is all rights reserved](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/blob/main/LICENSE) (The MIT Licence allows this).
> 
> In case you don't like this, I found another fork that still uses the MIT License and **supports 1.18**: [Inventory Rollback: Continued](https://github.com/Sidpatchy/InventoryRollback-Continued)
> 
> From the [README:](https://github.com/Sidpatchy/InventoryRollback-Continued/blob/master/README.md)
> 
> > Danjono, the plugin's original dev, seems to have disappeared off the face of the earth. I intend to maintain this fork in their absence. I will be manually merging pull requests (which I believe are of benefit to the plugin) from the original repo
> > Additionally the author of the other Inventory Rollback fork has licensed all their changes as all rights reserved. I disagree with that philosophy, the mere ability to publish our forks should demonstrate that copyleft licenses are a good thing
> 
> This means that once @danjono comes back, the changes can be merged back into the original plugin and there is no need to maintain the forks anymore.

Is this not pretty similar to the MIT licence? Just that he copyrights the changes he makes?

**Comment by libexus** [comment]
> > Please note that the fork @kalebchoi mentioned is **not licensed under the MIT Licence** anymore, [but is all rights reserved](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/blob/main/LICENSE) (The MIT Licence allows this).
> > In case you don't like this, I found another fork that still uses the MIT License and **supports 1.18**: [Inventory Rollback: Continued](https://github.com/Sidpatchy/InventoryRollback-Continued)
> > From the [README:](https://github.com/Sidpatchy/InventoryRollback-Continued/blob/master/README.md)
> > > Danjono, the plugin's original dev, seems to have disappeared off the face of the earth. I intend to maintain this fork in their absence. I will be manually merging pull requests (which I believe are of benefit to the plugin) from the original repo
> > > Additionally the author of the other Inventory Rollback fork has licensed all their changes as all rights reserved. I disagree with that philosophy, the mere ability to publish our forks should demonstrate that copyleft licenses are a good thing
> > 
> > 
> > This means that once @danjono comes back, the changes can be merged back into the original plugin and there is no need to maintain the forks anymore.
> 
> Is this not pretty similar to the MIT licence? Just that he copyrights the changes he makes?



The copyright is not the problem as long as a project is licensed under an open source license. Even this project is copyright'ed to danjono (See LICENCE). The "problem" is that the new code is "all rights reserved" instead of MIT which means that you mustn't modify or redistribute the new (TechnicallyCoded's) code.
